Repository devfile/devworkspace-operator, pull requests merged in 2020-09, with the labels that each got.

#147 Update the version to 1.0.0
  version/version.go
Labels: approved, lgtm

#148 Fix makefile update_devworkspace_crds rule
  Makefile
  update_devworkspace_crds.sh
Labels: approved, lgtm

#149 fix(README): typo on workspace as AFAIK it should be devworkspace 'Kind'
  README.md
Labels: approved, lgtm, needs-ok-to-test

#150 fix(yaml): avoid validation error
  deploy/service_account.yaml
Labels: approved, lgtm, ok-to-test

#151 feat(tls): Allow to skip insecure TLS config
  cmd/manager/main.go
  pkg/config/config.go
  pkg/config/property.go
Labels: approved, lgtm, needs-ok-to-test

#152 feat(ubi8): Upgrade ubi8 version to a grade A image
  build/Dockerfile
  build/rhel.Dockerfile
Labels: approved, lgtm, needs-ok-to-test

#154 Update version of master to 1.0.0-next
  version/version.go
Labels: approved, lgtm

#153 Change operator docker image name
  .cico/cico_openshift_e2e.sh
Labels: approved, lgtm

#155 Fix 'make start_local' rule and schema of theia sample
  Makefile
  samples/theia-nodejs.yaml
Labels: approved, lgtm

#156 Fix ci script and add operator image environment created by openshift ci
  .ci/openshift_e2e.sh
Labels: approved, lgtm

#157 feat(minikube) : better support out of the box with minikube
  Makefile
Labels: approved, lgtm, ok-to-test
