Repository devfile/devworkspace-operator, pull requests merged in 2020-06, with the labels that each got.

#109 Add OWNERS file
  OWNERS
Labels: lgtm

#96 Rework cert generation so that it uses two deployments
  .cico/cico_build_master.sh
  .cico/cico_build_nightly.sh
  Makefile
  cert-generation/Dockerfile
  cert-generation/main.go
  deploy/os/che-workspace-controller-cert-gen-deployment.yaml
  deploy/os/controller.yaml
  pkg/webhook/server/cert_cfg.go
  pkg/webhook/server/server.go
  pkg/webhook/server/webhook_cert_init.go
  pkg/webhook/workspace/config.go
Labels: ok-to-test

#110 Fix e2e errors
  test/e2e/cmd/workspaces_test.go
  test/e2e/pkg/client/pod.go
Labels: approved

#112 Rename config properties
  Makefile
  deploy/controller_config.yaml
  pkg/config/cmd_terminal.go
  pkg/config/doc.go
  pkg/config/property.go
Labels: approved, lgtm
