Repository devfile/devworkspace-operator, pull requests merged in 2020-12, with the labels that each got.

#207 Clean up accidental use of different logging package
  controllers/workspace/devworkspace_controller.go
  go.mod
  go.sum
Labels: approved, lgtm

#212 Fail devworkspace startup if we fail to download plugin metadata
  apis/controller/v1alpha1/component_types.go
  config/crd/bases/controller.devfile.io_components.yaml
  controllers/controller/component/component_controller.go
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/provision/components.go
  controllers/workspace/provision/data_types.go
  pkg/adaptor/errors.go
  pkg/adaptor/plugin.go
Labels: approved, lgtm

#215 Fix type in Makefile when evaluating plugin registry URL
  Makefile
Labels: approved

#211 Remove no-op mkdir init container
  controllers/workspace/provision/deployment.go
Labels: approved

#208 Add support for basic timing information on devworkspace start
  controllers/workspace/devworkspace_controller.go
  pkg/timing/annotations.go
  pkg/timing/timing.go
Labels: approved, lgtm

#224 Cert manager in README & fix a typo in Makefile
  README.md
Labels: approved, lgtm

#226 Use nightly machine execs for all webterminal plugin versions
  config/components/manager/manager.yaml
Labels: approved, lgtm

#202 Improve test e2e scenario
  .ci/openshift_e2e.sh
  Makefile
  go.mod
  go.sum
  test/e2e/cmd/workspaces_test.go
  test/e2e/pkg/client/client.go
  test/e2e/pkg/client/devws.go
  test/e2e/pkg/client/namespace.go
  test/e2e/pkg/client/oc.go
  test/e2e/pkg/client/pod.go
  test/e2e/pkg/client/rbac.go
  test/e2e/pkg/config/config.go
  test/e2e/pkg/deploy/controller.go
  test/e2e/pkg/deploy/deploy.go
  test/e2e/pkg/tests/cloud_shell_tests.go
  test/e2e/pkg/tests/devworkspaces_tests.go
Labels: approved, ok-to-test

#231 Switch base builder image to quay.io
  build/Dockerfile
Labels: approved, lgtm

#233 Add makefile rule for checking formatting
  .github/workflows/pr.yml
  Makefile
Labels: approved, lgtm

#225 Implement clonePath according to the devfile API
  apis/controller/v1alpha1/devfile.go
  controllers/workspace/restapis/devfilev1.go
  controllers/workspace/restapis/devfilev1_test.go
Labels: approved, lgtm
