Repository devfile/devworkspace-operator, pull requests merged in 2021-04, with the labels that each got.

#369 #19334 use :no_entry_sign: or...
  .github/workflows/release.yml
Labels: approved, lgtm

#372 Add Theia sample DevWorkspaces that use published yaml for Theia
  samples/flattened_theia-nodejs.yaml
  samples/plugins/vscode-typescript.yaml
  samples/plugins/vsx-installer.yaml
  samples/theia-latest.yaml
  samples/theia-next.yaml
  samples/with-k8s-ref/theia-nodejs.yaml
Labels: approved, lgtm

#368 Cherry-pick/adapt commit 2860ca66 (PR#330)
  pkg/webhook/deployment.go
  webhook/workspace/handler/immutable.go
Labels: approved, lgtm

#378 use version.go file to store the actual version
  make-release.sh
  version/version.go
Labels: approved, lgtm

#382 CRW-1671 can't sparsely checkout if the...
  update_devworkspace_crds.sh
Labels: approved, lgtm

#380 add missing copyright headers, make rhel-based go compilation arch-aware; update to ubi 8.3; merge changes in dockerfile -> rhel.dockerfile so they're BOTH updated (and the rhel one actually works!)
  .gitignore
  build/Dockerfile
  build/rhel.Dockerfile
Labels: approved, lgtm

#359 Add Che happy-path selenium test as PR check
  .ci/common.sh
  .ci/oci-devworkspace-happy-path.sh
  .ci/openshift_e2e.sh
  .ci/resources/htpasswdProvider.yaml
  .ci/resources/pod-che-happy-path.yaml
  .ci/resources/users.htpasswd
Labels: approved, lgtm, ok-to-test

#387 Fix info in PR template about e2e tests as PR checks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#381 Fail devworkspace start if devfile is invalid
  pkg/provision/storage/commonStorage.go
Labels: approved

#386 Add messages to true conditions and propagate them to DW info
  controllers/workspace/condition.go
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/status.go
Labels: approved, lgtm

#390 CRW-1654 update all RPMs
  build/Dockerfile
  build/rhel.Dockerfile
Labels: lgtm

#389 Fix .gitattributes to correctly mark generated files
  .gitattributes
Labels: approved, lgtm

#375 DevWorkspace should be failed when its pod has CrashLoopBackOff status
  controllers/workspace/condition.go
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/finalize.go
  controllers/workspace/predicates.go
  controllers/workspace/provision/data_types.go
  controllers/workspace/provision/deployment.go
  controllers/workspace/status.go
Labels: approved, lgtm

#394 Configure Dependabot for Dockerfiles
  .github/dependabot.yml
Labels: approved

#395 Simplify condition handling for DevWorkspaces
  controllers/workspace/condition.go
  controllers/workspace/status.go
Labels: approved

#396 Enable concurrent reconciles
  controllers/controller/devworkspacerouting/devworkspacerouting_controller.go
  controllers/workspace/devworkspace_controller.go
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/templates/components/manager/manager.yaml
  pkg/config/env.go
Labels: approved

#404 Fix local run and debug
  Makefile
Labels: approved, lgtm

#402 Set the project clone RELATED_IMAGE env var on releases
  Makefile
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/generate-deployment.sh
  deploy/templates/base/manager_image_patch.yaml
  make-release.sh
Labels: approved, lgtm
