Repository devfile/devworkspace-operator, pull requests merged in 2021-07, with the labels that each got.

#467 fix: fixes test cases title & restructure files
  pkg/library/container/container_test.go
  pkg/library/container/testdata/component/converts-all-fields.yaml
  pkg/library/container/testdata/component/ignores-non-container-components.yaml
  pkg/library/container/testdata/container/endpoints-common-port.yaml
  pkg/library/container/testdata/container/init-container-distinct-container-by-events.yaml.yaml
  pkg/library/container/testdata/container/resources-error-cpu-limit-less-than-request.yaml
  pkg/library/container/testdata/container/resources-error-invalid-memorylimit.yaml
  pkg/library/container/testdata/container/resources-error-memory-limit-less-than-requst.yaml
  pkg/library/container/testdata/container/resources-fixes-memory-limit-less-than-default-request.yaml
  pkg/library/container/testdata/container/resources-handles-cpu-and-memory.yaml
  pkg/library/container/testdata/parent/error-has-parent.yaml
  pkg/library/container/testdata/plugin/error-has-plugins.yaml
  pkg/library/container/testdata/volume/container-that-mounts-projects-directly.yaml
  pkg/library/container/testdata/volume/mountSources.yaml
Labels: approved

#472 Don't remove openshift-operators namespace on make uninstall
  build/make/deploy.mk
Labels: approved, lgtm

#480 fix: Add several fixes to the release process
  make-release.sh
Labels: approved, lgtm

#486 Fix run/debug locally
  build/make/deploy.mk
Labels: approved, lgtm

#481 fix: finetune regex in the release script
  make-release.sh
Labels: approved, lgtm

#449 feat: take into account bundle yaml in PR check
  .github/workflows/pr.yml
  build/make/olm.mk
Labels: approved, lgtm

#492 Use git binary for fetch to make ssh easier
  project-clone/internal/git/operations.go
  project-clone/internal/shell/execute.go
Labels: approved, lgtm

#494 Ignore VolumeMount order in containers when checking deployment sync
  controllers/workspace/provision/deployment.go
Labels: approved, lgtm

#498 Fix panic in webhooks server when patching workspace with nil Labels
  webhook/workspace/handler/workspace.go
Labels: approved, lgtm

#499 Disable 'experimental features' in default builds
  deploy/bundle/manifests/devworkspace-controller-configmap_v1_configmap.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-configmap.ConfigMap.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-configmap.ConfigMap.yaml
  deploy/templates/base/config.properties
Labels: approved, lgtm

#511 Update CSV description to remove TODO links
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
Labels: approved, lgtm

#510 Fix make run/debug locally in k8s
  build/make/deploy.mk
Labels: approved, lgtm

#505 Fix happy path test by adaption to Che Operator changes
  .ci/oci-devworkspace-happy-path.sh
Labels: approved

#519 Use ubi minimal as the default pvc_clean_job image
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/templates/components/manager/manager.yaml
Labels: approved, lgtm

#521 Remove icon from manifests
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
Labels: approved, lgtm

#524 chore: Update Mattermost GH Action to 1.1.0 version
  .github/workflows/release.yml
Labels: lgtm

#523 Add home directory to project clone container
  project-clone/Dockerfile
Labels: approved, lgtm

#526 Update bundle to be 0.8.0
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
Labels: approved, lgtm

#522 Update controller resources and concurrency
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/templates/components/manager/manager.yaml
Labels: approved, lgtm

#527 Avoid unnecessary condition updates when status is 'Unknown'
  controllers/workspace/status.go
Labels: approved, lgtm

#537 Bump version in main branch to v0.9.0+dev
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm
