Repository devfile/devworkspace-operator, pull requests merged in 2021-03, with the labels that each got.

#285 Remove stopped-by annotation when a workspace is restarted
  pkg/controller/workspace/workspace_controller.go
Labels: approved, lgtm

#282 Set memory request and cpu request/limit for PVC clean up job
  controllers/workspace/finalize.go
Labels: approved

#287 Hard code values for redundant related images
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/templates/components/manager/manager.yaml
  internal-registry/eclipse/cloud-shell/nightly/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal-dev/4.5.0/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal-dev/nightly/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal/nightly/devworkspacetemplate.yaml
Labels: approved, lgtm

#286 Fix temporary vsx-installer entrypoint after adding messages
  pkg/library/flatten/testdata/k8s-ref/nodejs-workspace.yaml
  samples/flattened_theia-next.yaml
  samples/flattened_theia-nodejs.yaml
  samples/plugins/vsx-installer.yaml
Labels: approved

#291 Fix go mod PR check
  .github/workflows/pr.yml
  go.sum
Labels: approved, lgtm

#293 [v1.0.0-alphax] Hard code values for redundant related images
  deploy/k8s/controller.yaml
  deploy/os/controller.yaml
  internal-registry/eclipse/cloud-shell/nightly/meta.yaml
  internal-registry/redhat-developer/web-terminal-dev/4.5.0/meta.yaml
  internal-registry/redhat-developer/web-terminal-dev/nightly/meta.yaml
Labels: approved, lgtm

#289 Remove need for componentDescriptions except for che-rest-apis sidecar
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/provision/routing.go
  pkg/library/shim/component.go
Labels: approved

#290 Update README.md
  README.md
Labels: approved, ok-to-test

#295 removing che-rest-api-sidecar
  controllers/controller/workspacerouting/solvers/common.go
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/finalize.go
  controllers/workspace/provision/deployment.go
  controllers/workspace/provision/routing.go
  controllers/workspace/restapis/component.go
  controllers/workspace/restapis/configmap.go
  controllers/workspace/restapis/devfilev1.go
  controllers/workspace/restapis/devfilev1_test.go
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-configmap.ConfigMap.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-configmap.ConfigMap.yaml
  deploy/templates/base/config.properties
  pkg/common/naming.go
  pkg/config/config.go
  pkg/config/constants.go
  pkg/config/property.go
  pkg/library/shim/component.go
Labels: approved, ok-to-test

#299 Skip ideUrl health check when DW does not specify ideURL
  controllers/workspace/status.go
Labels: approved, lgtm

#306 Remove trailing whitespace from make-release.sh
  make-release.sh
Labels: approved, lgtm

#316 Release scripts fixes
  .github/workflows/release.yml
  make-release.sh
Labels: approved, lgtm

#311 Rework generate-deployment to take a default image parameter
  deploy/generate-deployment.sh
  make-release.sh
Labels: approved, lgtm

#315 Ask confirmation before pushing next image
  .ci/openshift_e2e.sh
  Makefile
  README.md
  deploy/generate-deployment.sh
  deploy/templates/base/manager_image_patch.yaml
  deploy/templates/kustomize.pu
Labels: approved

#319 Use sigs.k8s.io/yaml to fix yamls unmarshalling
  go.mod
  go.sum
  pkg/config/cmd_terminal.go
  pkg/controller/workspace/restapis/configmap.go
  pkg/internal_registry/registry.go
Labels: approved, lgtm

#317 using coputil
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/finalize.go
  go.mod
  go.sum
Labels: approved, lgtm

#323 Fix make-release.sh errors
  make-release.sh
Labels: approved, lgtm

#309 readiness and liveness probes
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/templates/components/manager/manager.yaml
  main.go
  pkg/webhook/deployment.go
  webhook/main.go
Labels: approved

#325 Sync makefile and default deployment CRDs versions
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/kubernetes/objects/devworkspacetemplates.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/objects/devworkspacetemplates.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/generate-deployment.sh
Labels: approved, lgtm

#326 Fix accidentally applying flattened DW to cluster in reconcile
  controllers/workspace/devworkspace_controller.go
Labels: approved, lgtm

#331 Check that cert-manager is installed when installing on k8s
  Makefile
Labels: approved, lgtm

#339 feat(che-theia): Use machine-exec provided by theia
  samples/flattened_theia-next.yaml
  samples/flattened_theia-nodejs.yaml
Labels: approved, lgtm

#340 fix hanging terminal
  pkg/constants/constants.go
  pkg/webhook/deployment.go
  webhook/server/server.go
Labels: approved, lgtm

#335 fix hanging terminal
  pkg/config/constants.go
  pkg/webhook/deployment.go
  webhook/server/server.go
Labels: approved, lgtm

#336 Remove Component CRD and related code
  apis/controller/v1alpha1/component.go
  apis/controller/v1alpha1/component_types.go
  apis/controller/v1alpha1/devfile.go
  apis/controller/v1alpha1/runtime.go
  apis/controller/v1alpha1/zz_generated.deepcopy.go
  controllers/controller/devworkspacerouting/solvers/common.go
  controllers/controller/devworkspacerouting/solvers/openshift_oauth_solver.go
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/status.go
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/components.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/components.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/templates/crd/bases/controller.devfile.io_components.yaml
  deploy/templates/crd/kustomization.yaml
  patch/patch_crds.sh
Labels: approved, lgtm

#348 Improve release script
  .github/workflows/release.yml
  make-release.sh
Labels: lgtm

#349 Fix release.yaml formatting
  .github/workflows/release.yml
Labels: approved, lgtm

#351 Fix for untracked VERSION file
  make-release.sh
Labels: approved, lgtm

#343 Fixups to async storage
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/finalize.go
  controllers/workspace/provision/object.go
  controllers/workspace/provision/rbac.go
  pkg/provision/storage/doc.go
  pkg/provision/storage/shared.go
Labels: approved, lgtm

#358 chore(tweak(bugfix)) don't attempt to popd if we didn't pushd first; reuse variable
  make-release.sh
Labels: approved, lgtm

#329 Introduce latest web terminal plugin version
  internal-registry/redhat-developer/web-terminal-dev/latest/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal/latest/devworkspacetemplate.yaml
  samples/web-terminal-custom-tooling.yaml
  samples/web-terminal-dev.yaml
  samples/web-terminal.yaml
Labels: approved

#363 Fix usage of logger in finalize.go
  controllers/workspace/finalize.go
Labels: approved, lgtm

#355 Add terminating phase for workspaces waiting on finalizers
  controllers/workspace/finalize.go
Labels: approved, lgtm

#362 cleaning up workspace on failure
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/provision/deployment.go
Labels: approved, lgtm

#330 Permit changes to labels/annotations in restricted-access DevWorkspaces
  webhook/workspace/handler/immutable.go
Labels: approved, lgtm
