Repository devfile/devworkspace-operator, pull requests merged in 2021-02, with the labels that each got.

#256 feat(ingress): Check that ingress addon is enabled when using minikube
  Makefile
Labels: approved, lgtm, needs-ok-to-test

#255 Propagate devworkspace CR reference as env vars
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/env/common_env_vars.go
  pkg/library/shim/component.go
Labels: approved

#251 Make the service definition for endpoints public and make it slightly more versatile.
  controllers/controller/workspacerouting/solvers/basic_solver.go
  controllers/controller/workspacerouting/solvers/common.go
  controllers/controller/workspacerouting/solvers/openshift_oauth_solver.go
Labels: approved

#253 Enable the solvers to do the finalization of a workspace routing themselves.
  controllers/controller/workspacerouting/solvers/basic_solver.go
  controllers/controller/workspacerouting/solvers/cluster_solver.go
  controllers/controller/workspacerouting/solvers/openshift_oauth_solver.go
  controllers/controller/workspacerouting/solvers/solver.go
  controllers/controller/workspacerouting/solvers/sync_oauthclients.go
  controllers/controller/workspacerouting/workspacerouting_controller.go
Labels: approved, lgtm

#259 Let the solver getter set up the controller manager
  controllers/controller/workspacerouting/solvers/solver.go
  controllers/controller/workspacerouting/workspacerouting_controller.go
Labels: approved, lgtm

#276 Add Stopped By Annotation to ignored immutable fields
  pkg/config/constants.go
  webhook/workspace/handler/immutable.go
Labels: approved, lgtm

#278 Allow read for workspacerouting and watch/list for dw
  controllers/workspace/provision/rbac.go
Labels: approved, lgtm

#279 Migrate from master to main branch
  .github/workflows/dockerimage-next.yml
  .github/workflows/pr.yml
  README.md
Labels: approved, lgtm

#280 Initialize annotations if they are nil before setting the timer
  controllers/workspace/devworkspace_controller.go
Labels: approved, lgtm

#272 Explicitly set the routing class in the workspace routings so that external solvers can be used if specified as the default routing class
  controllers/controller/workspacerouting/solvers/solver.go
  controllers/controller/workspacerouting/workspacerouting_controller.go
  controllers/workspace/provision/routing.go
Labels: approved, lgtm
