Repository devfile/devworkspace-operator, pull requests merged in 2021-05, with the labels that each got.

#393 Improve dwo versioning
  .dockerignore
  Makefile
  build/Dockerfile
  build/rhel.Dockerfile
  deploy.mk
  main.go
  version/version.go
  webhook/main.go
Labels: approved

#414 Remove makefile targets duplicated between deploy.mk and Makefile
  Makefile
Labels: approved, lgtm

#411 Rename internal env vars in make-release for consistency
  make-release.sh
Labels: approved, lgtm

#421 Rework version info to work without a `.git` directory
  Makefile
  build/make/deploy.mk
  build/make/version.mk
Labels: approved, lgtm

#420 Grab all env vars in manager.yaml when using make run/debug
  build/make/deploy.mk
Labels: approved

#426 bump to latest ubi8-minimal:8.3-298.1618432845; add URLs into dockerfiles so that updateBaseImages.sh can suggest updates in all dockerfiles
  build/Dockerfile
  build/rhel.Dockerfile
  project-clone/Dockerfile
Labels: approved, lgtm

#427 Upgrade the project to use go 1.14
  build/Dockerfile
  build/rhel.Dockerfile
  go.mod
Labels: approved, lgtm

#423 Rename ideUrl to mainUrl
  Makefile
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/status.go
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/generate-deployment.sh
  go.mod
  go.sum
Labels: approved, lgtm

#431 [Selenium] Stabilize happy-path test, add devworkspace-che logs to test report
  .ci/common.sh
  .ci/oci-devworkspace-happy-path.sh
  .ci/resources/pod-che-happy-path.yaml
Labels: approved, lgtm, ok-to-test

#430 Finalize main endpoint type movement
  apis/controller/v1alpha1/devfile.go
  controllers/workspace/status.go
  internal-registry/eclipse/cloud-shell/nightly/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal-dev/4.5.0/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal-dev/latest/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal-dev/nightly/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal/4.5.0/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal/latest/devworkspacetemplate.yaml
  internal-registry/redhat-developer/web-terminal/nightly/devworkspacetemplate.yaml
  pkg/library/container/testdata/converts-all-fields.yaml
  pkg/library/flatten/testdata/k8s-ref/already-flattened.yaml
  pkg/library/flatten/testdata/k8s-ref/nodejs-workspace.yaml
  pkg/library/flatten/testdata/k8s-ref/web-terminal-with-plugin.yaml
  samples/flattened_theia-next.yaml
  samples/flattened_web-terminal-dev.yaml
  samples/flattened_web-terminal.yaml
  samples/plugins/theia-next.yaml
  samples/plugins/web-terminal-dev.yaml
  samples/plugins/web-terminal.yaml
Labels: approved

#433 Rework generate-deployment.sh to be simpler
  deploy/generate-deployment.sh
Labels: approved, lgtm

#424 Fix starting a workspace once it enters the failed state
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/finalize.go
  controllers/workspace/status.go
Labels: approved

#417 Automount configmaps/secrets into devworkspaces
  controllers/workspace/provision/deployment.go
  pkg/constants/metadata.go
Labels: approved, lgtm

#439 Remove unused plugin broker image
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-configmap.ConfigMap.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-configmap.ConfigMap.yaml
  deploy/templates/base/config.properties
Labels: approved, lgtm

#437 Move storage type setting to devfile attributes
  pkg/constants/metadata.go
  pkg/provision/storage/asyncStorage.go
  pkg/provision/storage/provisioner.go
  samples/plugins/theia-next.yaml
  samples/with-k8s-ref/async-theia-next.yaml
Labels: approved, lgtm
