Repository devfile/devworkspace-operator, pull requests merged in 2021-09, with the labels that each got.

#568 Use up to date che sample for happy path test
  .ci/oci-devworkspace-happy-path.sh
Labels: lgtm, approved

#566 fix: Always append service account dockerconfig to the devworkspace
  controllers/workspace/devworkspace_controller.go
  pkg/provision/workspace/pull_secret.go
Labels: lgtm, approved

#570 Adapt PR template to OpenShift version upgrade
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#557 chore: Update to ubi8-minimal:8.4-208 and ubi8/go-toolset:1.15.14-3
  build/Dockerfile
  project-clone/Dockerfile
Labels: lgtm, approved

#569 adapt release action to make-release.sh changes
  .github/workflows/release.yml
Labels: lgtm, approved

#555 Validate incoming devfiles
  .vscode/launch.json
  README.md
  build/make/deploy.mk
  controllers/workspace/devworkspace_controller.go
  samples/theia-latest.yaml
  samples/theia-next.yaml
  samples/web-terminal.yaml
  webhook/workspace/handler/validate.go
  webhook/workspace/validate.go
  webhook/workspace/validating_cfg.go
Labels: lgtm, approved

#574 Change tag image on next for getting last changes in the test codebase
  .ci/resources/pod-che-happy-path.yaml
Labels: lgtm, approved

#573 Fix typo in release github action
  .github/workflows/release.yml
Labels: approved

#575 Add dockerfile for prow CI
  .ci/oci.Dockerfile
Labels: approved

#582 Fixup edge cases in automounting git credentials
  pkg/provision/workspace/automount/common.go
  pkg/provision/workspace/automount/git-credentials.go
  pkg/provision/workspace/deployment.go
Labels: lgtm, approved

#587 Workaround issue where makefile can't run commands after oc logout
  build/make/deploy.mk
Labels: lgtm, approved

#588 Fail controller startup when conflicting webhook definition present
  build/make/deploy.mk
  pkg/webhook/init_cfg.go
Labels: lgtm, approved

#591 fix: typo in the olm.mk
  build/make/olm.mk
Labels: lgtm, approved, needs-ok-to-test

#589 docs: Adding instructinon for switching to the right namespace
  README.md
Labels: lgtm, approved, needs-ok-to-test

#590 docs: Adding skopeo to the prerequisites
  README.md
Labels: lgtm, approved, needs-ok-to-test

#592 doc: fixing a typo in the grafana port-forwarding instructions
  doc/grafana/README.md
Labels: lgtm, approved, needs-ok-to-test

#594 fix: Update devworkspace git credentials automounting to only use one conf…
  pkg/provision/workspace/automount/common.go
  pkg/provision/workspace/automount/git-credentials.go
  pkg/provision/workspace/deployment.go
Labels: lgtm, approved

#596 Fix typo in metrics documentation
  doc/grafana/README.md
Labels: lgtm, approved

#601 Document how to use a custom controller image in generated OLM bundle
  README.md
  deploy/generate-deployment.sh
Labels: lgtm, approved

#600 Reformat variable using spaces as indentation for directives
  Makefile
  build/make/deploy.mk
  build/make/olm.mk
Labels: lgtm, approved

#609 Fix checking exit code of happy path test
  .ci/che-happy-path.sh
Labels: lgtm, approved

#608 Add basic issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: lgtm, approved

#622 Fixup theia samples to avoid need to for a proxy
  samples/theia-latest.yaml
  samples/theia-next.yaml
Labels: lgtm, approved

#605 Introduce timeout for hanging workspaces
  apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/status.go
  deploy/bundle/manifests/controller.devfile.io_devworkspaceoperatorconfigs.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspaceoperatorconfigs.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspaceoperatorconfigs.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/templates/crd/bases/controller.devfile.io_devworkspaceoperatorconfigs.yaml
  pkg/config/defaults.go
  pkg/config/sync.go
Labels: lgtm, approved
