Repository devfile/devworkspace-operator, pull requests merged in 2022-05, with the labels that each got.

#831 Fix command to install goimports in Go 1.16
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: lgtm, approved

#833 fix: prevent storage class attribute modification
  pkg/provision/storage/provisioner.go
  webhook/workspace/handler/workspace.go
Labels: approved, needs-ok-to-test

#832 Add v0.14.0 and v0.14.1 bundles to main branch
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.14.0.bundle.yaml
  olm-catalog/release/devworkspace-operator.v0.14.1.bundle.yaml
Labels: lgtm, approved

#837 feat: configmap option for perWorkspace PVC size
  pkg/provision/config/config.go
  pkg/provision/storage/perWorkspaceStorage.go
Labels: lgtm, approved, needs-ok-to-test

#840 fix: Adding 'KUBERNETES_SERVICE_HOST' env var to the 'no_proxy / NO_PROXY' list
  pkg/library/env/workspaceenv.go
Labels: lgtm, approved

#842 fix: updating che-machine-exec tag in the sample
  samples/flattened_theia-next.yaml
  samples/flattened_web-terminal-dev.yaml
  samples/flattened_web-terminal.yaml
Labels: lgtm, approved

#834 feat: cleanup shared PVC when no longer in use
  pkg/provision/storage/commonStorage.go
  pkg/provision/storage/shared.go
Labels: lgtm, approved, needs-ok-to-test

#827 Configurable default PVC size for common and per-workspace storage classes
  apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go
  apis/controller/v1alpha1/zz_generated.deepcopy.go
  deploy/bundle/manifests/controller.devfile.io_devworkspaceoperatorconfigs.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspaceoperatorconfigs.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspaceoperatorconfigs.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/templates/crd/bases/controller.devfile.io_devworkspaceoperatorconfigs.yaml
  pkg/config/defaults.go
  pkg/config/sync.go
  pkg/provision/storage/commonStorage_test.go
  pkg/provision/storage/perWorkspaceStorage.go
  pkg/provision/storage/shared.go
Labels: lgtm, approved, needs-ok-to-test
