Repository devfile/devworkspace-operator, pull requests merged in 2022-06, with the labels that each got.

#850 Ignore order of envFrom when comparing deployments
  pkg/provision/sync/diffopts.go
Labels: lgtm, approved

#851 stop reconciling workspace when PVC cleanup job fails
  controllers/workspace/finalize.go
Labels: approved

#860 fix: ignore order of volumeMounts when comparing deployments
  pkg/provision/sync/diffopts.go
Labels: lgtm, approved

#854 Allow changing workspace storage type in some cases
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/finalize.go
  pkg/constants/finalizers.go
  webhook/workspace/handler/workspace.go
Labels: approved

#861 Fix goimports install command in release pipeline
  .github/workflows/release.yml
Labels: lgtm, approved

#864 Update release GH action to set up Go correctly
  .github/workflows/release.yml
Labels: lgtm, approved

#870 Fix issue where deleting a workspace deletes the PVC incorrectly
  pkg/provision/storage/commonStorage.go
Labels: lgtm, approved

#846 Report error when common PVC cleanup job hangs
  pkg/library/status/check.go
  pkg/provision/storage/cleanup.go
  pkg/provision/workspace/deployment.go
Labels: ok-to-test, lgtm, approved
