Repository devfile/devworkspace-operator, pull requests merged in 2022-04, with the labels that each got.

#803 Update delve installation instructions. Fix #801
  README.md
Labels: ok-to-test, approved

#805 Remove install_crds mention from README. Fix #800
  README.md
Labels: ok-to-test, approved

#811 docs: Convert additional documenation to adoc and add Table of Contents
  docs/additional-configuration.adoc
Labels: approved

#813 docs: Adding info about smoke tests
  docs/release/README.md
Labels: lgtm, approved

#817 Temporarily disable validation of DevWorkspaces to workaround api issue
  controllers/workspace/devworkspace_controller.go
Labels: lgtm, approved

#815 chore: Set version of 'next' bundle to always update and add build info
  .github/workflows/next-build.yml
Labels: lgtm, approved

#820 fix: broken additional-configuration README link
  README.md
Labels: lgtm, approved, needs-ok-to-test

#823 cherry-pick: Pull changes from PR #821 into 0.14.x branch
  Makefile
  deploy/bundle/manifests/workspace.devfile.io_devworkspaces.yaml
  deploy/bundle/manifests/workspace.devfile.io_devworkspacetemplates.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/kubernetes/objects/devworkspacetemplates.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/objects/devworkspacetemplates.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/generate-deployment.sh
  go.mod
  go.sum
Labels: lgtm, approved

#822 docs: Adding SOP for updating devfile API
  README.md
Labels: approved

#824 Update git credentials documentation to not mention Theia directly
  docs/additional-configuration.adoc
Labels: lgtm, approved

#818 feat: 'one PVC per-workspace' storage class
  docs/additional-configuration.adoc
  pkg/common/naming.go
  pkg/constants/constants.go
  pkg/provision/storage/commonStorage_test.go
  pkg/provision/storage/perWorkspaceStorage.go
  pkg/provision/storage/perWorkspaceStorage_test.go
  pkg/provision/storage/provisioner.go
  pkg/provision/storage/shared.go
  pkg/provision/storage/testdata/perWorkspace-storage/can-make-projects-ephemeral.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/can-set-ephemeral-volume-size.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/does-nothing-for-no-storage-needed.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/error-duplicate-volumes.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/error-undefined-volume-init-container.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/error-undefined-volume.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/error-unparseable-ephemeral-size.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/handles-ephemeral-volumes.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/handles-projects-volume-ordering.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/projects-volume-overriding.yaml
  pkg/provision/storage/testdata/perWorkspace-storage/rewrites-volumes-for-perworkspace-pvc-strategy.yaml
  samples/theia-next_per-workspaceStorage.yaml
Labels: lgtm, approved, needs-ok-to-test

#829 Ensure automounted volume names are shorter than 63 characters
  pkg/common/naming.go
Labels: lgtm, approved
