Repository devfile/devworkspace-operator, pull requests merged in 2022-09, with the labels that each got.

#916 Ignore mount path for git-credentials secrets and mount as file
  pkg/provision/automount/gitconfig.go
  pkg/provision/automount/templates.go
Labels: lgtm, approved

#924 Log all non-default fields when updating config
  pkg/config/sync.go
Labels: approved

#927 fix: Allow switching to per-user or common strategy if the storage type is not defined
  webhook/workspace/handler/workspace.go
Labels: lgtm, approved

#932 Disable webhooks for updating storage-type in existing workspaces
  webhook/workspace/handler/workspace.go
Labels: lgtm, approved

#933 Cherry pick 932
  webhook/workspace/handler/workspace.go
Labels: approved

#934 Update base images according to PR #931
  build/Dockerfile
  project-clone/Dockerfile
Labels: approved

#938 fix: Treat Forbidden error as unrecoverable sync error
  pkg/provision/sync/sync.go
Labels: ok-to-test, approved
