Repository devfile/devworkspace-operator, pull requests merged in 2022-08, with the labels that each got.

#901 chore: Add bundles for v0.15.3
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.15.3.bundle.yaml
Labels: lgtm, approved

#902 Don't use "error" in message on status update conflict
  controllers/workspace/status.go
Labels: lgtm, approved

#907 fix: specify updated makefile rules for install via OLM
  README.md
Labels: lgtm

#910 Shorten sample catalogsource registry polling interval to 5m
  catalog-source.yaml
Labels: lgtm, approved

#908 feat: Add DWO icon for OperatorHub
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
Labels: lgtm, approved

#912 fix: update operatorhub icon
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
Labels: lgtm

#869 codeblock indentation on uninstall instructions
  docs/uninstall.md
Labels: approved, needs-ok-to-test
