Repository devfile/devworkspace-operator, pull requests merged in 2022-01, with the labels that each got.

#719 Fix async storage deployment after introducing cache limits
  pkg/provision/storage/asyncstorage/constants.go
  pkg/provision/storage/asyncstorage/deployment.go
  pkg/provision/storage/asyncstorage/service.go
  webhook/workspace/handler/metadata.go
Labels: lgtm, approved

#725 chore: update commit template to use...
  make-release.sh
Labels: lgtm, approved

#726 Remove jpinkney from codeowners
  .github/CODEOWNERS
  OWNERS
Labels: lgtm, approved

#727 Add v0.11.0 bundle from release to OLM catalog in main
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.11.0.bundle.yaml
Labels: lgtm, approved

#731 Fix issue where ephemeral projects volume is mounted twice in async
  pkg/provision/storage/asyncStorage.go
Labels: lgtm, approved

#733 Add @ibuziuk to codeowners
  .github/CODEOWNERS
Labels: lgtm, approved

#734 Use sync package for reconciling async storage service
  pkg/provision/storage/asyncStorage.go
  pkg/provision/storage/asyncstorage/service.go
  pkg/provision/sync/diff.go
Labels: lgtm, approved

#741 fix: Use git binary for checking out references to avoid go-git issues
  project-clone/internal/git/operations.go
  project-clone/internal/shell/execute.go
Labels: lgtm, approved

#746 fix: Increasing the default PVCStorageSize to 10Gi
  pkg/constants/constants.go
  pkg/provision/storage/commonStorage_test.go
Labels: lgtm, approved

#749 fix: Fixup copy-paste error in variable names
  controllers/controller/devworkspacerouting/sync_routes.go
  controllers/controller/devworkspacerouting/sync_services.go
Labels: lgtm, approved

#750 fix: Add support for syncing secrets in sync package
  pkg/provision/sync/diff.go
  pkg/provision/sync/diffopts.go
Labels: lgtm, approved

#756 Cherry-pick fixups to 0.12.x branch
  pkg/provision/storage/asyncStorage.go
  pkg/provision/storage/asyncstorage/sidecar.go
Labels: approved

#755 fix: Fixup issues with async storage in DevWorkspaces
  pkg/provision/storage/asyncStorage.go
  pkg/provision/storage/asyncstorage/sidecar.go
Labels: lgtm, approved

#761 fix: Allow to remove not started workspaces
  controllers/controller/devworkspacerouting/devworkspacerouting_controller.go
Labels: lgtm, approved, needs-ok-to-test

#763 chore: Remove out-of-date EPL licenses on some files
  pkg/config/common_test.go
  pkg/config/migrate.go
  pkg/config/migrate_test.go
  pkg/provision/automount/git-user-credentials.go
Labels: lgtm, approved

#758 chore: Add bundle for v0.12.0 release to main branch
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.12.0.bundle.yaml
Labels: lgtm, approved
