Repository devfile/devworkspace-operator, pull requests merged in 2023-07, with the labels that each got.

#1143 fix: replace deprecated Ingress annotation
  controllers/controller/devworkspacerouting/solvers/basic_solver.go
  controllers/controller/devworkspacerouting/solvers/common.go
Labels: ok-to-test, lgtm, approved

#1145 Wrap git credential helper to ignore 'store' and 'erase' operations
  pkg/provision/automount/templates.go
Labels: lgtm, approved

#1149 Add v0.21.2 bundle to 0.22.x branch before releasing v0.22.0
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.21.2.bundle.yaml
Labels: approved

#1150 Add bundle for v0.21.2 to main branch
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.21.2.bundle.yaml
Labels: lgtm, approved

#1153 Update GitHub Actions to new versions in order to use Node 16
  .github/workflows/code-coverage.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: lgtm, approved
