Repository devfile/devworkspace-operator, pull requests merged in 2023-06, with the labels that each got.

#1116 Cherry-pick changes from #1115 to 0.21.x branch
  project-clone/internal/git/operations.go
  project-clone/internal/shell/execute.go
Labels: approved

#1117 Copy v0.21.1 bundle to main branch
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.21.1.bundle.yaml
Labels: lgtm, approved

#1094 Update openshift-console-dashboard.json
  docs/grafana/openshift-console-dashboard.json
Labels: ok-to-test, lgtm, approved

#1125 Fix next build github action not including bundle in channel
  .github/workflows/next-build.yml
  build/scripts/build_digests_bundle.sh
Labels: approved

#1128 Fixup commands in next-build GH action to avoid failure.
  .github/workflows/next-build.yml
Labels: lgtm, approved

#1124 Add basis for future automated functional/regression tests of project-clone container
  project-clone/test/project-clone-test-basic.devworkspace.yaml
  project-clone/test/project-clone-test.devworkspace.yaml
Labels: approved

#1131 Ensure all samples have memory limit and request
  samples/code-latest.yaml
  samples/idea-latest.yaml
  samples/plain.yaml
  samples/theia-latest.yaml
Labels: lgtm, approved

#1135 Fixup PR check action for checking files format
  .github/workflows/pr.yml
Labels: lgtm, approved

#1136 Fix CRD types in aggregated view and edit clusterroles
  deploy/bundle/manifests/devworkspace-controller-edit-workspaces_rbac.authorization.k8s.io_v1_clusterrole.yaml
  deploy/bundle/manifests/devworkspace-controller-view-workspaces_rbac.authorization.k8s.io_v1_clusterrole.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-edit-workspaces.ClusterRole.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-view-workspaces.ClusterRole.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-edit-workspaces.ClusterRole.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-view-workspaces.ClusterRole.yaml
  deploy/templates/components/rbac/edit_workspaces_cluster_role.yaml
  deploy/templates/components/rbac/view_workspaces_cluster_role.yaml
Labels: lgtm, approved

#1140 Cherry-pick #1138 to 0.21.x branch
  controllers/workspace/devworkspace_controller.go
  pkg/provision/workspace/pull_secret.go
Labels: approved

#1138 Fix potential nil pointer dereference in reconcile loop
  controllers/workspace/devworkspace_controller.go
  pkg/provision/workspace/pull_secret.go
Labels: lgtm, approved
