Repository devfile/devworkspace-operator, pull requests merged in 2024-10, with the labels that each got.

#1326 fix: remove dummy caBundle from CRDs
  deploy/bundle/manifests/workspace.devfile.io_devworkspaces.yaml
  deploy/bundle/manifests/workspace.devfile.io_devworkspacetemplates.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/kubernetes/objects/devworkspacetemplates.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspaces.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/objects/devworkspacetemplates.workspace.devfile.io.CustomResourceDefinition.yaml
  deploy/templates/cert-manager/crd_webhooks_patch.yaml
  deploy/templates/olm/crd_webhooks_patch.yaml
  deploy/templates/service-ca/crd_webhooks_patch.yaml
Labels: lgtm, approved

#1321 feat: turn healthCheckHttpClient timeout from 500ms to 3s
  controllers/workspace/devworkspace_controller.go
  controllers/workspace/status.go
Labels: ok-to-test, lgtm, approved

#1329 Fix Start ssh-agent post start event
  pkg/constants/constants.go
  pkg/library/ssh/event.go
Labels: lgtm, approved, needs-ok-to-test
