Repository devfile/devworkspace-operator, pull requests merged in 2025-02, with the labels that each got.

#1368 docs: Adding 'DevWorkspace Operator on Developer Sandbox' section to …
  README.md
  img/dwo-on-developer-sandbox.png
  img/wto-on-developer-sandbox.png
Labels: lgtm

#1379 chore: update upload-artifact to v4
  .github/workflows/scorecard.yml
Labels: lgtm, approved

#1389 Update Go in e2e test Dockerfile to Go 1.22
  .ci/oci.Dockerfile
Labels: approved

#1390 Add gettext
  .ci/oci.Dockerfile
Labels: approved

#1369 Update project to use Go 1.22
  .github/workflows/code-coverage.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  Makefile
  apis/controller/v1alpha1/zz_generated.deepcopy.go
  deploy/bundle/manifests/controller.devfile.io_devworkspaceoperatorconfigs.yaml
  deploy/bundle/manifests/controller.devfile.io_devworkspaceroutings.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-role.ClusterRole.yaml
  deploy/deployment/kubernetes/objects/devworkspaceoperatorconfigs.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/kubernetes/objects/devworkspaceroutings.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-role.ClusterRole.yaml
  deploy/deployment/openshift/objects/devworkspaceoperatorconfigs.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/deployment/openshift/objects/devworkspaceroutings.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/templates/components/rbac/role.yaml
  deploy/templates/crd/bases/controller.devfile.io_devworkspaceoperatorconfigs.yaml
  deploy/templates/crd/bases/controller.devfile.io_devworkspaceroutings.yaml
  go.mod
  go.sum
Labels: approved

#1392 chore: add @akurinnoy to CODEOWNERS
  .github/CODEOWNERS
Labels: lgtm, approved

#1391 Update kube-rbac-proxy image to quay.io/brancz/kube-rbac-proxy:v0.13.1
  build/scripts/generate_deployment.sh
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/devworkspace-controller-manager.Deployment.yaml
  deploy/templates/components/csv/clusterserviceversion.yaml
Labels: lgtm, approved

#1395 chore: add go toolchain 1.22.0
  go.mod
Labels: approved

#1378 fix: auto-mount path collisions
  pkg/provision/automount/projected.go
Labels: lgtm, approved
