Repository devfile/devworkspace-operator, pull requests merged in 2025-06, with the labels that each got.

#1415 fix: common PVC cleanup job to be assigned to a correct node
  pkg/constants/constants.go
  pkg/provision/storage/cleanup.go
Labels: approved

#1441 test (controllers) : Dynamically construct envtest binary assets while preparing envtest environment (#1387)
  controllers/controller/devworkspacerouting/suite_test.go
  controllers/workspace/suite_test.go
Labels: ok-to-test, lgtm

#1447 Update base images to latest versions
  build/Dockerfile
  project-clone/Dockerfile
Labels: lgtm, approved

#1451 Fix documentation indentation
  docs/dwo-configuration.md
Labels: lgtm, approved

#1457 Cherry pick #1455 to 0.35.x branch
  pkg/provision/storage/cleanup.go
Labels: approved

#1460 Revert "Temporarily don't build new bundle image on next release"
  make-release.sh
Labels: approved

#1458 feat(Makefile): add optional WAIT=true env to until all operands are running (#1456)
  build/make/deploy.mk
Labels: lgtm, approved
