Repository devfile/devworkspace-operator, pull requests merged in 2025-05, with the labels that each got.

#1421 Configuring the DevWorkspace Cleanup Job
  docs/dwo-configuration.md
Labels: approved

#1416 chore: fix Dockerfile warnings reported during docker build
  build/Dockerfile
Labels: lgtm, approved

#1427 Update project to go 1.23
  .ci/oci.Dockerfile
  .github/workflows/code-coverage.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  build/Dockerfile
  go.mod
  project-clone/Dockerfile
Labels: approved

#1412 chore: Replace deprecated `ioutil.ReadFile` and `ioutil.ReadDir` in workspaceenv_test
  pkg/library/env/workspaceenv_test.go
Labels: ok-to-test, lgtm

#1425 Update golang.org/x/net to v0.38.0
  go.mod
  go.sum
Labels: lgtm, approved

#1432 Update python-version for release workflow
  .github/workflows/release.yml
Labels: approved

#1438 chore: add the workflow_dispatch event into devtools container build
  .github/workflows/devtools-image-build.yml
Labels: lgtm
