Repository devfile/devworkspace-operator, pull requests merged in 2025-09, with the labels that each got.

#1505 Update 0.36.0 changelog
  CHANGELOG.md
Labels: lgtm, approved

#1469 test (e2e) : Add basic E2E test scenario to verify dev workspace changes are persisted across restarts
  test/e2e/pkg/client/client.go
  test/e2e/pkg/client/devws.go
  test/e2e/pkg/client/oc.go
  test/e2e/pkg/client/pod.go
  test/e2e/pkg/tests/devworkspace_restart_tests.go
  test/e2e/pkg/tests/devworkspaces_tests.go
  test/resources/simple-devworkspace-with-project-clone.yaml
Labels: ok-to-test, lgtm, approved

#1511 Update changelog for v0.37.0
  CHANGELOG.md
Labels: approved

#1513 Add release and release-digest files for v0.37.0
  olm-catalog/release-digest/channel.yaml
  olm-catalog/release-digest/devworkspace-operator.v0.37.0.bundle.yaml
  olm-catalog/release/channel.yaml
  olm-catalog/release/devworkspace-operator.v0.37.0.bundle.yaml
Labels: lgtm, approved
