Repository devfile/devworkspace-operator, pull requests merged in 2025-03, with the labels that each got.

#1398 chore: temporarily set actions/cache version
  .github/workflows/release.yml
Labels: approved

#1400 chore: Update actions/cache to v3.4.3
  .github/workflows/code-coverage.yml
  .github/workflows/next-build.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: lgtm, approved

#1403 chore: Update actions/cache to v4
  .github/workflows/pr.yml
Labels: lgtm

#1406 chore: add go toolchain 1.22.0 (#1395)
  go.mod
Labels: lgtm, approved
